---
- name: Adding New Member to Load Balancer Pool
  gather_facts: no
  hosts: f5-host
  remote_user: root

  tasks:
    - name: Get the localhost facts
      setup:
      delegate_to: localhost

    - name: Create the node
      bigip_node:
        host: '{{ ansible_default_ipv4.address }}'
        name: '{{ ansible_hostname }}'
        password: iops123!
        server: 10.0.0.13
        user: admin
        validate_certs: no

    - name: Add node to the Pool
      bigip_pool_member:
        description: MNDR Application
        host: '{{ ansible_default_ipv4.address }}' # New IP address to be added to the pool
        name: '{{ ansible_fqdn }}' # Hostname of the new node to be added to the pool
        password: iops123! # F5 password
        pool: mndr_pool # Pool name where the new node will be addedd
        port: 3868 # port that the new member will listen to
        server: 10.0.0.13 #F5 server IP
        user: admin # F5 server username to use on login
        validate_certs: no

# Testing if the facts are correctly being taken from localhost
#    - name: ensure the hostname is copied to the file
#      lineinfile:
#        path: '/home/stack/test/ip_address'
#        state: present
#        mode: 0600
#        line: '{{ ansible_hostname }}'
#      delegate_to: localhost
#
#    - name: ensure the address is copied to the file
#      lineinfile:
#        path: '/home/stack/test/ip_address'
#        state: present
#        mode: 0600
#        line: '{{ ansible_default_ipv4.address }}'
#      delegate_to: localhost
